# Generated by Django 5.1.1 on 2024-10-01 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0004_alter_event_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='event_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='cus_ph',
            field=models.CharField(max_length=10),
        ),
    ]
