# Generated by Django 5.1.1 on 2024-10-01 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0005_booking_event_name_alter_booking_cus_ph'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='event_name',
        ),
    ]
