# Generated by Django 5.1.1 on 2024-10-01 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0007_rename_name_booking_event_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='event_name',
            new_name='name',
        ),
    ]
